name: google-adk
on:
  push:

jobs:
  quickstart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: davidkhala/uv-buildpack@main
        with:
          working-directory: agent/adk
      - run: uv run adk web
        working-directory: agent/adk


